### ISSUE TITLE
Speed prediction with accelerometer

### ISSUE THREAD

**Issue by jpeddicord** [jpeddicord/speedofsound#1]
Filing this as an issue for later. Want to see if we're able to adjust the volume a little bit before we get GPS updates for an even smoother volume curve. Not sure how possible it is, but I'd like to think there's a way.

This issue is free for the taking if some brave soul wants to give it a try.

**Comment by jpeddicord** [comment]
This project is in maintenance mode and this feature is unlikely to happen. If you're interested in working on this, feel free to comment and/or email me.

**Comment by Lee-Carre** [comment]
> If you're interested in working on this, feel free to comment …

That's far less likely when the ticket is prematurely closed 😄.
