### ISSUE TITLE
Support OBD-II scanners as a speed source

### ISSUE THREAD

**Issue by jpeddicord** [jpeddicord/speedofsound#23]
Some OBD2 tools support Bluetooth natively, and are rather cheap. SoS could optionally connect with these and use them as a speed source instead of GPS, which would greatly improve battery life.

**Comment by jpeddicord** [comment]
This project is in maintenance mode and this feature is unlikely to happen. If you're interested in working on this, feel free to comment and/or email me.

**Comment by Lee-Carre** [comment]
> If you're interested in working on this, feel free to comment …

That's far less likely when the ticket is prematurely closed 😄.
