### ISSUE TITLE
switch on Bluetooth automatically when driving by car (by GPS or GSM [prefered] speed)

### ISSUE THREAD

**Issue by toxtox** [jpeddicord/speedofsound#25]
Most of the day I do not need bluetooth and therefore bluetooth is switched off.
When I drive by car I have to enable bluetooth manually and somethimes I forget it to enable.

**Would it be possible to switch on bluetooth at a defined driving speed for example 30km/h or faster?
And switching it off again if speed is lower then for example 25km/h after a delay of 15minutes?**

My GPS is normally disabled, too and as an alternative I use the less precise GSM location by cell id ( https://github.com/n76/Local-GSM-Backend/blob/HEAD/README.md ).

Theroretically the speed calculation should work with GSM-cell-id-locations in the same way as with GPS, but I suppose that the speed calculation can only give you a decent speed result after a few kilometers.

But switching on bluetooth automatically after a few kilometers would be much better for me then forgetting it completely.

**Comment by jpeddicord** [comment]
This is probably a little bit out-of-scope for Speed of Sound, and having it constantly monitor your location while not activated (if I read your issue correctly) would drain the battery a bit more quickly.

_However_, you could potentially automate this using Tasker:

* Detect when your "activity" (walk/run/etc) changes -- this is apparently provided by Google's location services
* Enable/disable Bluetooth based on the location activity type

This may or may not be a part of Tasker itself, but at the very least there's a Tasker plugin called AutoLocation that may serve your needs. Additionally, I've found this Reddit thread that describes your scenario; you might find some helpful solutions in there: https://www.reddit.com/r/tasker/comments/4i6we8/request_car_bluetooth_activation/

**Comment by toxtox** [comment]
Thanks for you replay and your proposal with the tasker.
I know tasker is a really powerful and famous tool and could maybe do the job. But unfortunately it is not open-source.

> This is probably a little bit out-of-scope for Speed of Sound

According to the app "_Preferences_" Speed of Sound can use bluetooth devices too. 
**So in my point of view it could make sense to have an option to enable / (disable) bluetooth automatically depending on driving speed.**

> ...constantly monitor your location while not activated (if I read your issue correctly) would drain the battery a bit more quickly.

**But Speed of Sound itself needs a location dectection for calculation the driving speed, too?**
**I guess the additional battery drain will not be a big issue?**

**Comment by toxtox** [comment]
If your decision against an automated bluetooth toggling option is not final yet, you could reduce the time and effort for creating the bluetooth-toggling-source-code by using the toggling function of the opensource app **_LibreTasks_** as a template:
https://github.com/biotinker/LibreTasks

**Comment by jpeddicord** [comment]
Sorry, I don't think this is something I want to pursue. I want to keep the app's purpose simple; this feature seems to fit a very specific use case that other applications already cover.

**Comment by Lee-Carre** [comment]
@toxtox

> I know tasker is a really powerful and famous tool and could maybe do the job. But unfortunately it is not open-source.

+1

There are some [other] libre automation apps in the F-Droid repository, which I think could do as you wish.
* Easer (very capable, but horrible UX)
* Automation [literally, that's its actual name] (simpler, but much better usability)
* A2DP Volume (various conditional-config of Bluetooth)
