### ISSUE TITLE
Bluetooth devices and "music enabled" Bluetooth devices

### ISSUE THREAD

**Issue by atom-smasher** [jpeddicord/speedofsound#26]
(1) I can't select my "UE BOOM 2" as a "music enabled" Bluetooth device. But I don't even want to; (2) I want to select my "Edge 1000" (bike computer) as a Bluetooth device so the app will switch itself on/off depending on whether or not I'm on the bike (with the Edge-1000 turned on).

Making the app respond to *any* Bluetooth device will solve both of those problems.

Thanks...

**Comment by jpeddicord** [comment]
Thanks for the report. I'm planning on doing a release for Android 8 soon; should be able to sneak this in.

**Comment by jpeddicord** [comment]
Fix committed. Will be in an upcoming release (less than 2 weeks away)
