### ISSUE TITLE
Doesn't request coarse location

### ISSUE THREAD

**Issue by sdfg2** [jpeddicord/speedofsound#37]
Just upgraded to RR Pie, 7.0.2 on two different handsets.  In both cases, although SoS requests location permissions (which were given), it never gets a GPS lock.  After double checking the permissions in Privacy Guard, it says that coarse location has never been requested, despite being allowed.

I had a quick look in matlog and couldn't see anything, but I'm not sure what I should be looking for.  There were a couple of errors about missing assets.

Any advice?

**Comment by jpeddicord** [comment]
This is actually intentional; coarse location isn't accurate enough to determine your velocity correctly. (At least, that was the case when this was originally implemented, and is likely to still be the case for lower-end devices.)

**Comment by sdfg2** [comment]
I'm sorry, my explanation was a misreading on my part.

When I checked Privacy Guard it only lists 'coarse location' inside the entry for SoS, but in the overall location tab it says coarse and fine.  The problem is Privacy Guard is reporting that it's not requesting location at all, and gets stuck on "waiting for GPS signal".

**Comment by Lee-Carre** [comment]
Could this be an issue with “RR Pie, 7.0.2”?

I don't experience the problem described in the OP, on Android (Samsung's stock distro) when installing from F-Droid.

For clarity, the (location) permissions requested (& granted) according to Android's App Info are
* fine location in foreground
* coarse location in foreground
* location in background
